### ISSUE TITLE
Windows : ImageMagick 7.0.1.5 problème de build

### ISSUE THREAD

**Issue by benoitrenaud** [absolunet/nwayo#17]
**Voici l'erreur obtenu lors du rebuild :**
`
events.js:160
     throw er; // Unhandled 'error' event
     ^
Error: Stream yields empty buffer
   at Socket.<anonymous> (C:\wamp\www\nwayo\node_modules\gm\lib\command.js:57:1
7)
   at emitNone (events.js:91:20)
   at Socket.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:926:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)`

Sour Windows 7 et 8.1 après une mise à jour complète de pwen et choco.

**Comment by jblandry** [comment]
En attente de l'update du module gm: https://github.com/aheckmann/gm/issues/559

**Comment by rbrlortie** [comment]
Works correctly when using the command "-PackageParameters LegacySupport=true" during Chocolatey install.

**Comment by jblandry** [comment]
Corrected via #36
