### ISSUE TITLE
Rebuild not working on 3.6.0-rc.3

### ISSUE THREAD

**Issue by thierry2015** [absolunet/nwayo#50]
When updating from RC1 to RC3, the rebuild command doesn't work.

```bash
$ nwayo rebuild
C:\work\sites\rsl\nwayo\node_modules\@absolunet\nwayo-workflow\helpers\util.js:404
                }, globalUsage.tasks));
                               ^

TypeError: Cannot read property 'tasks' of undefined
    at Util.initCli (C:\work\sites\rsl\nwayo\node_modules\@absolunet\nwayo-workflow\helpers\util.js:404:18)
    at module.exports (C:\work\sites\rsl\nwayo\node_modules\@absolunet\nwayo-workflow\cli.js:20:7)
    at module.exports (C:\Users\tparent\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\index.js:283:32)
    at Object.<anonymous> (C:\Users\tparent\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\bin\nwayo:4:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
```

The global nwayo-cli version is 1.4.0

**Comment by thierry2015** [comment]
The global package @absolunet/nwayo-cli must be at the "next" version.

`npm i  -g @absolunet/nwayo-cli@next`

The official version (probably 1.5.0) should be released at the same time as nwayo 3.6.0
