### ISSUE TITLE
Nwayo CLI update doesn't work with the update command

### ISSUE THREAD

**Issue by thierry2015** [absolunet/nwayo#54]
**Specs**
- Nwayo workflow/toolbox version: 3.6.1
- Nwayo CLI version: 3.6.0-rc.3
- Nwayo CLI target version: 3.6.1
- OS: Windows 10 64 bits

**Issue**
If I run `nwayo update`, the CLI update starts correctly and stops with the following error:
```
Update available: 3.6.0-rc.3 → 3.6.1

Updating...

removed 596 packages in 5.593s
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN rollback Rolling back extend-shallow@2.0.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\(me)\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\node_modules\union-value\node_modules'
npm ERR! path C:\Users\(me)\AppData\Roaming\npm\nwayo
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\(me)\AppData\Roaming\npm\nwayo'
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Users\(me)\AppData\Roaming\npm\nwayo']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, open 'C:\Users\(me)\AppData\Roaming\npm\nwayo'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'open',
npm ERR!      path: 'C:\\Users\\(me)\\AppData\\Roaming\\npm\\nwayo' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, open \'C:\\Users\\(me)\\AppData\\Roaming\\npm\\nwayo\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\(me)\\AppData\\Roaming\\npm\\nwayo' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(me)\AppData\Roaming\npm-cache\_logs\2019-01-20T20_47_57_433Z-debug.log
(node:33380) UnhandledPromiseRejectionWarning: Error: Cannot find module '@absolunet/terminal'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Util.exit (C:\Users\(me)\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\helpers\util.js:102:21)
    at UpdateNotifier.util.checkUpdate [as callback] (C:\Users\(me)\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\index.js:67:10)
    at checkNpm.then.catch.err (C:\Users\(me)\AppData\Roaming\npm\node_modules\@absolunet\nwayo-cli\node_modules\update-notifier\index.js:72:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems that `@absolunet/terminal` package is used when not available during the process.

**Request**
_As a developer, I want to be able to run the update command to easily update the CLI in order to prevent manual installation and migration mistakes_

**Comment by rbrlortie** [comment]
I have a similar issue where running `nwayo update` finishes without errors but still prompts `Update available: 3.6.0-rc.3 → 3.6.1` after completion.

```
Update available: 3.6.0-rc.3 → 3.6.1
Run nwayo update to upgrade
```

...

```
kara@KLORTIE-PC:/mnt/c/xampp/htdocs/magento/nwayo$ nwayo update
No update available
Reinstalling... 
```

...

```
Update available: 3.6.0-rc.3 → 3.6.1
Run nwayo update to upgrade
```


`C:\xampp\htdocs\magento\nwayo\node_modules\@absolunet\nwayo-workflow\package.json` has `"version": "3.6.1"` so I don't know what is triggering the prompt.



```
kara@KLORTIE-PC:/mnt/c/xampp/htdocs/magento/nwayo$ npm list -g --depth 0
/usr/lib
├── @absolunet/nwayo-cli@3.6.1
├── npm@6.5.0
└── npx@10.2.0

kara@KLORTIE-PC:/mnt/c/xampp/htdocs/magento/nwayo$ npm list --depth 0
robotshop@ /mnt/c/xampp/htdocs/magento/nwayo
└── @absolunet/nwayo-workflow@3.6.1
```
