### ISSUE TITLE
**Describe the bug** "nwayo rebuild" is unable to complete. Here's the error:

### ISSUE THREAD

**Issue by poojac26** [absolunet/nwayo#59]
...nwayo\node_modules\async-done\index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Gulp.emit (events.js:171:17)
    at Gulp.EventEmitter.emit (domain.js:441:20)
    at Object.error (...nwayo\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (...nwayo\node_modules\now-and-later\lib\map.js:50:14)
    at f (...nwayo\node_modules\once\once.js:25:25)
    at f (...nwayo\node_modules\once\once.js:25:25)
    at tryCatch (...nwayo\node_modules\async-done\index.js:24:15)
    at done (...nwayo\node_modules\async-done\index.js:40:12)
    at Domain.onError (...nwayo\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:273:13)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:441:20)
    at Transform.EventEmitter.emit (domain.js:454:12)
    at Transform.onerror (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Transform.emit (events.js:182:13)
    at Transform.EventEmitter.emit (domain.js:441:20)
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at Transform.afterTransform (_stream_transform.js:94:3)
    at Transform.transform [as _transform] (...nwayo\node_modules\gulp-eslint\index.js:64:4)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Transform.Writable.write (_stream_writable.js:294:11)
    at DestroyableTransform.ondata (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at addChunk (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_transform.js:91:10)
    at DestroyableTransform.transform [as _transform] (...nwayo\node_modules\gulp-line-ending-corrector\index.coffee:40:6)
    at DestroyableTransform.Transform._read (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (...nwayo\node_modules\gulp-line-ending-corrector\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at addChunk (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform._transform (...nwayo\node_modules\gulp-cached\index.js:43:10)
    at DestroyableTransform.Transform._read (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (...nwayo\node_modules\gulp-cached\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (...nwayo\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at addChunk (...nwayo\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...nwayo\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (...nwayo\node_modules\to-through\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (...nwayo\node_modules\to-through\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at Pumpify.onReadable (...nwayo\node_modules\to-through\index.js:25:14)
    at Pumpify.emit (events.js:182:13)
    at Pumpify.EventEmitter.emit (domain.js:459:23)
    at emitReadable_ (...nwayo\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:504:10)
    at emitReadable (...nwayo\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:498:62)
    at addChunk (...nwayo\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:298:29)
    at readableAddChunk (...nwayo\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Pumpify.Readable.push (...nwayo\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at Pumpify.Duplexify._forward (...nwayo\node_modules\duplexify\index.js:170:26)
    at DestroyableTransform.onreadable (...nwayo\node_modules\duplexify\index.js:134:10)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at emitReadable_ (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:504:10)
    at emitReadable (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:498:62)
    at addChunk (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:298:29)
    at readableAddChunk (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:91:10)
    at DestroyableTransform.addSourcemap [as _transform] (...nwayo\node_modules\vinyl-fs\lib\src\sourcemap.js:12:14)
    at DestroyableTransform.Transform._read (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at addChunk (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (...nwayo\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:91:10)
    at onRead (...nwayo\node_modules\vinyl-fs\lib\src\read-contents\index.js:45:14)
    at onReadFile (...nwayo\node_modules\vinyl-fs\lib\src\read-contents\read-buffer.js:21:5)
    at ...nwayo\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

when I run [18:43:17] Starting task assets-images-highdensity it is taking long time I need to do CTRL+C to cancle and same for also
OS: Windows 10 
Steps to reproduce: run nwayo rebuild
many times it ask me for system permission
![image](https://user-images.githubusercontent.com/61976329/76217948-59f35a80-6239-11ea-9e66-6be488c9d6bd.png)

**Comment by jblandry** [comment]
Seems to be a problem with ImageMagick/GraphicsMagick local binaries
